<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>UAssetViewer.CefHelper</RootNamespace>
    <AssemblyName>CefHelper</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Another.Unofficial.Xilium.CefGlue" Version="0.4.0" />
  </ItemGroup>
</Project>
